### ISSUE TITLE
What is the status of this plugin?

### ISSUE THREAD

**Issue by arasbm** [psychobunny/nodebb-plugin-badges#1]
I was wondering if this plugin was ready. I tried searching for it from ACP but I could not find it in the list of available plugins, so I am guessing this has not been published to npm yet, right?

**Comment by psychobunny** [comment]
Not published, and we've since created a rewards system in NodeBB, so that means I'm going to have to rewrite how I did this. That said, there is a similar badges plugin: https://community.nodebb.org/topic/4355/nodebb-plugin-ns-points-ns-points-forum-gamification
